- platform: template
  sensors:
    purpleair_aqi:
      friendly_name: 'PurpleAir AQI'
      value_template: >
        {% macro calcAQI(Cp, Ih, Il, BPh, BPl) -%}
          {{ (((Ih - Il)/(BPh - BPl)) * (Cp - BPl) + Il)|round }}
        {%- endmacro %}
        {% set pm25 = states('sensor.purpleair_pm25')|float %}
        {% if pm25 > 1000 %}
          invalid
        {% elif pm25 > 350.5 %}
          {{ calcAQI(pm25, 500.0, 401.0, 500.0, 350.5) }}
        {% elif pm25 > 250.5 %}
          {{ calcAQI(pm25, 400.0, 301.0, 350.4, 250.5) }}
        {% elif pm25 > 150.5 %}
          {{ calcAQI(pm25, 300.0, 201.0, 250.4, 150.5) }}
        {% elif pm25 > 55.5 %}
          {{ calcAQI(pm25, 200.0, 151.0, 150.4, 55.5) }}
        {% elif pm25 > 35.5 %}
          {{ calcAQI(pm25, 150.0, 101.0, 55.4, 35.5) }}
        {% elif pm25 > 12.1 %}
          {{ calcAQI(pm25, 100.0, 51.0, 35.4, 12.1) }}
        {% elif pm25 >= 0.0 %}
          {{ calcAQI(pm25, 50.0, 0.0, 12.0, 0.0) }}
        {% else %}
          invalid
        {% endif %}
      unit_of_measurement: "AQI"
      availability_template: "{{ sensor.purpleair_pm25 }}"

    purpleair_description:
      friendly_name: 'PurpleAir AQI Description'
      value_template: >
        {% set aqi = states('sensor.purpleair_aqi')|float %}
        {% if aqi >= 401.0 %}
          Very Hazardous
        {% elif aqi >= 301.0 %}
          Hazardous
        {% elif aqi >= 201.0 %}
          Very Unhealthy
        {% elif aqi >= 151.0 %}
          Unhealthy
        {% elif aqi >= 101.0 %}
          Unhealthy for Sensitive Groups
        {% elif aqi >= 51.0 %}
          Moderate
        {% elif aqi >= 0.0 %}
          Good
        {% else %}
          unknown
        {% endif %}
      availability_template: "{{ sensor.purpleair_pm25 }}"

    open_windows_count:
      friendly_name: "Open Windows"
      value_template: >-
        {{
          (expand('group.window_sensors') | selectattr('state', 'eq', 'open')  | list | length | int) +
          (expand('group.window_sensors') | selectattr('state', 'eq', 'on') | list | length | int)
        }}
      icon_template: >-
        {% if (states("sensor.open_windows_count") | int) > 0 %}
          mdi:window-open
        {% else %}
          mdi:window-closed
        {% endif %}
