# Bathroom Switch: 6bb5a898a3e7dd142d9b794601947f80

- alias: Bathroom Switch - On
  mode: single
  trigger:
    - trigger: device
      device_id: 6bb5a898a3e7dd142d9b794601947f80
      domain: button
      entity_id: event.bathroom_switch_up
      type: pressed
  action:
    - action: scene.turn_on
      target:
        entity_id: scene.bathroom_bright

- alias: Bathroom Switch - Off
  trigger:
    - trigger: device
      device_id: 6bb5a898a3e7dd142d9b794601947f80
      domain: button
      entity_id: event.bathroom_switch_down
      type: pressed
  action:
    - action: scene.turn_on
      target:
        entity_id: scene.bathroom_off
