- alias: Bathroom Switch - On
  use_blueprint:
    path: soffes/event_scene.yaml
    input:
      event: event.bathroom_switch_up
      scene: scene.bathroom_bright

- alias: Bathroom Switch - Off
  use_blueprint:
    path: soffes/event_scene.yaml
    input:
      event: event.bathroom_switch_down
      scene: scene.bathroom_off
