- alias: Bathroom Switch - On
  use_blueprint:
    path: soffes/event_scene.yaml
    input:
      event: event.bathroom_switch_up
      scene: scene.bathroom_bright

- alias: Bathroom Switch - Off
  use_blueprint:
    path: soffes/event_scene.yaml
    input:
      event: event.bathroom_switch_down
      scene: scene.bathroom_off

# Toggle vanity light
- alias: Bathroom Switch - Config
  trigger:
    - trigger: state
      entity_id: event.bathroom_switch_config
  action:
    - action: light.toggle
      target:
        entity_id: light.vanity_switch
