- alias: Bedroom Switch - On
  mode: single
  trigger:
    - platform: device
      domain: mqtt
      device_id: 29d3d5e3e454095c6fd24afddb6e6920
      type: action
      subtype: release_4
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.bedroom_bright

- alias: Bedroom Switch - Off
  mode: single
  trigger:
    - platform: device
      domain: mqtt
      device_id: 29d3d5e3e454095c6fd24afddb6e6920
      type: action
      subtype: release_3
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.bedroom_off

- alias: Bedroom Closet - Open
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_closet_door
      from: "off"
      to: "on"
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.bedroom_closet_on

- alias: Bedroom Closet - Closed
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_closet_door
      from: "on"
      to: "off"
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.bedroom_closet_off
