- alias: Bedroom Switch - On
  mode: single
  trigger:
    - trigger: state
      entity_id: light.bedroom_switch
      to: "on"
  action:
    - action: scene.turn_on
      target:
        entity_id: scene.bedroom_bright

- alias: Bedroom Switch - Off
  trigger:
    - trigger: state
      entity_id: light.bedroom_switch
      to: "off"
  action:
    - action: scene.turn_on
      target:
        entity_id: scene.bedroom_off

# - alias: Bedroom Closet - Open
#   mode: single
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.bedroom_closet_door
#       from: "off"
#       to: "on"
#   action:
#     - service: scene.turn_on
#       target:
#         entity_id: scene.bedroom_closet_on

# - alias: Bedroom Closet - Closed
#   mode: single
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.bedroom_closet_door
#       from: "on"
#       to: "off"
#   action:
#     - service: scene.turn_on
#       target:
#         entity_id: scene.bedroom_closet_off

- alias: Bedroom Closet Switch - On
  mode: single
  trigger:
    - trigger: state
      entity_id: light.bedroom_closet_switch
      to: "on"
  action:
    - action: scene.turn_on
      target:
        entity_id: scene.bedroom_closet_on

- alias: Bedroom Closet Switch - Off
  mode: single
  trigger:
    - trigger: state
      entity_id: light.bedroom_closet_switch
      to: "off"
  action:
    - action: scene.turn_on
      target:
        entity_id: scene.bedroom_closet_off
