# Doorbell

- alias: Doorbell - Motion
  mode: single
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.doorbell_motion
      from: "off"
  conditions:
    - condition: sun
      after: sunset
  actions:
    - action: scene.turn_on
      target:
        entity_id: scene.front_porch_motion

- alias: Doorbell - Clear
  mode: single
  triggers:
    - trigger: state
      entity_id:
        - binary_sensor.doorbell_motion
      to: "off"
      from: "on"
  actions:
    - delay: 00:02:00
    - action: light.turn_off
      target:
        entity_id: light.front_porch

# Front Door

- alias: Front Door - Unlocked
  mode: single
  triggers:
    - trigger: state
      entity_id:
        - lock.front_door
      to: unlocked
  conditions:
    - condition: sun
      after: sunset
  actions:
    - action: scene.turn_on
      target:
        entity_id: scene.front_porch_motion

- alias: Front Door - Locked
  mode: single
  triggers:
    - trigger: state
      entity_id:
        - lock.front_door
      to: locked
  conditions:
    - condition: sun
      after: sunset
  actions:
    - delay: 00:02:00
    - action: light.turn_off
      target:
        entity_id: light.front_porch
