- alias: Hallway Switch - On
  use_blueprint:
    path: soffes/event_scene.yaml
    input:
      event: event.hallway_switch_up
      scene: scene.hallway_bright

- alias: Hallway Switch - Off
  use_blueprint:
    path: soffes/event_scene.yaml
    input:
      event: event.hallway_switch_down
      scene: scene.hallway_off
