# Kitchen Switch

- alias: Kitchen Switch - On
  use_blueprint:
    path: soffes/event_scene.yaml
    input:
      event: event.kitchen_switch_up
      scene: scene.kitchen_bright

- alias: Kitchen Switch - Off
  use_blueprint:
    path: soffes/event_scene.yaml
    input:
      event: event.kitchen_switch_down
      scene: scene.kitchen_off

# Countertop Switch

- alias: Kitchen Countertop Switch - On
  use_blueprint:
    path: soffes/event_scene.yaml
    input:
      event: event.countertop_switch_up
      scene: scene.kitchen_countertop_bright

- alias: Kitchen Countertop Switch - Off
  use_blueprint:
    path: soffes/event_scene.yaml
    input:
      event: event.countertop_switch_down
      scene: scene.kitchen_countertop_off
