- alias: Living Room Switch - On
  use_blueprint:
    path: soffes/event_scene.yaml
    input:
      event: event.living_room_switch_up
      scene: scene.living_room_bright

- alias: Living Room Switch - Off
  use_blueprint:
    path: soffes/event_scene.yaml
    input:
      event: event.living_room_switch_down
      scene: scene.living_room_off
