- alias: Office Switch - On
  use_blueprint:
    path: soffes/event_scene.yaml
    input:
      event: event.office_switch_up
      scene: scene.office_bright

- alias: Office Switch - Off
  use_blueprint:
    path: soffes/event_scene.yaml
    input:
      event: event.office_switch_down
      scene: scene.office_off
