- alias: Shed Door Sensor
  use_blueprint:
    path: soffes/binary_sensor_scene.yaml
    input:
      binary_sensor: binary_sensor.shed_door
      on_scene: scene.shed_door_open
      off_scene: scene.shed_door_closed
