- alias: Leave Home
  trigger:
    - platform: state
      entity_id: person.sam
      to: "not_home"
  action:
    - service: climate.turn_off
      entity_id: climate.hallway
    - service: script.turn_on
      entity_id: media_player.sonos
