- alias: Studio Switch - On
  use_blueprint:
    path: soffes/event_scene.yaml
    input:
      event: event.studio_switch_up
      scene: scene.studio_full

- alias: Studio Switch - Off
  use_blueprint:
    path: soffes/event_scene.yaml
    input:
      event: event.studio_switch_down
      scene: scene.studio_off

- alias: Studio Switch - Config
  use_blueprint:
    path: soffes/event_scene.yaml
    input:
      event: event.studio_switch_config
      scene: scene.studio_bright

# - alias: Studio Sensor
#   use_blueprint:
#     path: soffes/binary_sensor_scene.yaml
#     input:
#       binary_sensor: binary_sensor.studio_door
#       on_scene: scene.studio_bright
#       off_scene: scene.studio_off
