- alias: Studio Switch - On
  trigger:
    - trigger: device
      domain: mqtt
      device_id: 724b60fe72d65fca7ce2a653e42afbfa
      type: action
      subtype: release_4
  action:
    - service: scene.turn_on
      target:
        entity_id: scene.studio_bright

- alias: Studio Switch - Off
  trigger:
    - trigger: device
      domain: mqtt
      device_id: 724b60fe72d65fca7ce2a653e42afbfa
      type: action
      subtype: release_3
  action:
    - action: scene.turn_on
      target:
        entity_id: scene.studio_off
