substitutions:
  name: "garage-door"
  friendly_name: Garage Door
packages:
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25iboard.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret garage_door_encryption_key


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
